# default rules
homepage:
  url:   /
  param: { module: membre, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

ajax_search_members:
  url:   membre/ajaxlist
  param: { module: membre, action: ajaxlist }