default:
  http_metas:
    content-type: text/html

  metas:
    title:        Piwam
    description:  Gestionnaire d'association
    language:     fr

  stylesheets:    [main.css, pagination.css]

  javascripts:    [scriptaculous/lib/prototype.js, scriptaculous/src/scriptaculous.js, scriptaculous/src/effect.js]

  has_layout:     on
  layout:         layout
