
# -----------------------------------------------------------------------------
#     MISC ACTIONS
# -----------------------------------------------------------------------------

mailing:
  url:    /mailing
  param:  { module: mailing, action: index }
  
error_credentials:
  url:    /error/credentials
  param:  { module: error, action: credentials }
  

# -----------------------------------------------------------------------------
#     PIWAM ACTIONS
# ----------------------------------------------------------------------------- 

login:
  url:    /login
  param:  { module: association, action: login }

logout:
  url:    /logout
  param:  { module: association, action: logout }
  
retrieve_password:
  url:    /recuperer_mot_de_passe
  param:  { module: association, action: forgottenpassword }
  
setup:
  url:    /install
  param:  { module: install, action: index }

update:
  url:    /update
  param:  { module: update, action: index }

config:
  url:    /config
  param:  { module: association, action: config }
  

# -----------------------------------------------------------------------------
#     FINANCIAL RELATED ACTIONS
# -----------------------------------------------------------------------------
  
balance:
  url:   /bilan
  param: { module: association, action: bilan }


  
activities_list:
  url:    /activites
  param:  { module: activite, action: index }

activity_by_id:
  url:    /activite/details/:id
  param:  { module: activite, action: show }

activity_edit:
  url:    /activite/editer/:id
  param:  { module: activite, action: edit }

activity_delete:
  url:    /activite/supprimer/:id
  param:  { module: activite, action: delete }
  
activity_new:
  url:    /activite/creer
  param:  { module: activite, action: new }



accounts_list:
  url:    /comptes
  param:  { module: compte, action: index }

account_by_id:
  url:    /compte/details/:id
  param:  { module: compte, action: show }

account_edit:
  url:    /compte/editer/:id
  param:  { module: compte, action: edit }

account_delete:
  url:    /compte/supprimer/:id
  param:  { module: compte, action: delete }

account_new:
  url:    /compte/nouveau
  param:  { module: compte, action: new }



expenses_list:
  url:    /depenses
  param:  { module: depense, action: index }

incomes_list:
  url:    /recettes
  param:  { module: recette, action: index }

  
  
  
# -----------------------------------------------------------------------------
#     MEMBER ACTIONS
# -----------------------------------------------------------------------------
  
members_list:
  url:    /membres
  param:  { module: membre, action: index}
  
members_map:
  url:    /carte
  param:  { module: membre, action: map }
  
faces:
  url:    /trombinoscope
  param:  { module: membre, action: faces }
  
ajax_search_members:
  url:    membre/ajaxlist
  param:  { module: membre, action: ajaxlist }

register_first_member:
  url:    /register_first_member
  param:  { module: membre, action: newfirst }

member_by_id:
  url:    /membre/details/:id
  param:  { module: membre, action: show }


# -----------------------------------------------------------------------------
#     ASSOCIATION ACTIONS
# -----------------------------------------------------------------------------
 
associations_list:
  url:    /associations
  param:  { module: association, action: index }


  
# -----------------------------------------------------------------------------
#     STATUS ACTIONS
# -----------------------------------------------------------------------------
 
status_list:
  url:    /statuts
  param:  { module: statut, action: index }

  
# -----------------------------------------------------------------------------
#     DUE ACTIONS
# -----------------------------------------------------------------------------
 
dues_list:
  url:    /cotisations
  param:  { module: cotisation, action: index }

due_show:
  url:    /cotisation/details
  param:  { module: cotisation, action: show }

due_edit:
  url:    /cotisation/editer
  param:  { module: cotisation, action: edit }
  
due_delete:
  url:    /cotisation/supprimer
  param:  { module: cotisation, action: delete }

# -----------------------------------------------------------------------------
#     DUETYPE ACTIONS
# -----------------------------------------------------------------------------
 
duetypes_list:
  url:    /types_cotisations
  param:  { module: cotisationtype, action: index }



# -----------------------------------------------------------------------------
#     EXPORT ACTIONS
# -----------------------------------------------------------------------------
 
export:
  url:    /export
  param:  { module: export, action: index }

  
# -----------------------------------------------------------------------------
#     DEFAULT ACTIONS
# -----------------------------------------------------------------------------

homepage:
  url:    /
  param:  { module: membre, action: index }

  
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*