default:
  http_metas:
    content-type: text/html

  metas:
    title:        Piwam
    description:  Gestionnaire d'association
    language:     fr

  stylesheets:    [main.css, menu.css, pagination.css, form.css, table.css, buttons.css, overlay.css, jquery-ui-1.7.1/smoothness/jquery-ui-1.7.1.custom.css]

  #javascripts:	  [scriptaculous/lib/prototype.js, scriptaculous/src/effects.js]
  javascripts:    [tiny_mce/tiny_mce.js, jquery-ui-1.7.1/js/jquery-1.3.2.min.js, jquery-ui-1.7.1/js/jquery-ui-1.7.1.custom.min.js, boxover/boxover.js, jquery-tools/jquery.tools.min.js]

  has_layout:     true
  layout:         layout
